# Generated by Django 4.2.2 on 2023-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField(max_length=150)),
                ('data_criacao', models.DateField()),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Apicultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField(max_length=150)),
                ('data_criacao', models.DateField()),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Informatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField(max_length=150)),
                ('data_criacao', models.DateField()),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
    ]
